[package]
name = "painter_data"
version = "0.1.0"
edition = "2018"


[lib]
name = "painter_data"
crate-type = ["lib", "cdylib"]

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
