[package]
name = "painter_depgraph"
version = "0.1.0"
edition = "2018"


[lib]
name = "painter_depgraph"
crate-type = ["lib", "cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[features]
