[package]
name = "painter_core"
version = "0.1.0"
edition = "2018"


[lib]
name = "painter_core"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.14.5"
features = ["extension-module"]

[dependencies]
glow = "0.11.0"
libc = "0.2.105"
painter_data = { path = "../painter-data" }
